package com.baway.liuheng.dialog;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.baway.liuheng.dialog.bean.ImgBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IMG_BEAN".
*/
public class ImgBeanDao extends AbstractDao<ImgBean, Long> {

    public static final String TABLENAME = "IMG_BEAN";

    /**
     * Properties of entity ImgBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Img = new Property(0, Long.class, "Img", true, "_id");
        public final static Property Url = new Property(1, String.class, "Url", false, "URL");
    }


    public ImgBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ImgBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IMG_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: Img
                "\"URL\" TEXT);"); // 1: Url
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IMG_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ImgBean entity) {
        stmt.clearBindings();
 
        Long Img = entity.getImg();
        if (Img != null) {
            stmt.bindLong(1, Img);
        }
 
        String Url = entity.getUrl();
        if (Url != null) {
            stmt.bindString(2, Url);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ImgBean entity) {
        stmt.clearBindings();
 
        Long Img = entity.getImg();
        if (Img != null) {
            stmt.bindLong(1, Img);
        }
 
        String Url = entity.getUrl();
        if (Url != null) {
            stmt.bindString(2, Url);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ImgBean readEntity(Cursor cursor, int offset) {
        ImgBean entity = new ImgBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // Img
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // Url
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ImgBean entity, int offset) {
        entity.setImg(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ImgBean entity, long rowId) {
        entity.setImg(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ImgBean entity) {
        if(entity != null) {
            return entity.getImg();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ImgBean entity) {
        return entity.getImg() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
